<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Equipment;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $equipment = [
            // Kitchen Equipment
            [
                'equipment_id' => 1,
                'name' => 'Commercial Gas Stove',
                'code' => 'EQP-001',
                'category' => 'Kitchen Equipment',
                'description' => '6-burner commercial gas stove',
                'total_quantity' => 5,
                'location' => 'Main Kitchen - Station A',
                'model' => 'GS-6000',
                'serial_number' => 'SN-GS6000-001',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(2),
                'is_active' => true,
            ],
            [
                'equipment_id' => 2,
                'name' => 'Convection Oven',
                'code' => 'EQP-002',
                'category' => 'Kitchen Equipment',
                'description' => 'Commercial convection oven for baking and roasting',
                'total_quantity' => 3,
                'location' => 'Main Kitchen - Baking Section',
                'model' => 'CO-3000',
                'serial_number' => 'SN-CO3000-003',
                'condition' => 'Excellent',
                'last_maintenance' => now()->subMonths(1),
                'is_active' => true,
            ],
            [
                'equipment_id' => 3,
                'name' => 'Industrial Refrigerator',
                'code' => 'EQP-003',
                'category' => 'Storage Equipment',
                'description' => 'Large-capacity refrigerator for ingredient storage',
                'total_quantity' => 8,
                'location' => 'Main Kitchen - Cold Storage',
                'model' => 'IR-5000',
                'serial_number' => 'SN-IR5000-005',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(3),
                'is_active' => true,
            ],
            [
                'equipment_id' => 4,
                'name' => 'Commercial Mixer',
                'code' => 'EQP-004',
                'category' => 'Kitchen Equipment',
                'description' => 'Heavy-duty mixer for dough and batter preparation',
                'total_quantity' => 2,
                'location' => 'Main Kitchen - Preparation Area',
                'model' => 'CM-2000',
                'serial_number' => 'SN-CM2000-002',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(4),
                'is_active' => true,
            ],
            [
                'equipment_id' => 5,
                'name' => 'Food Processor',
                'code' => 'EQP-005',
                'category' => 'Kitchen Equipment',
                'description' => 'Large-capacity food processor for bulk preparation',
                'total_quantity' => 2,
                'location' => 'Main Kitchen - Prep Area',
                'model' => 'FP-3000',
                'serial_number' => 'SN-FP3000-001',
                'condition' => 'Excellent',
                'last_maintenance' => now()->subMonths(1),
                'is_active' => true,
            ],
            
            // Dining & Service Equipment
            [
                'equipment_id' => 6,
                'name' => 'Buffet Table Set',
                'code' => 'EQP-006',
                'category' => 'Service Equipment',
                'description' => 'Complete buffet table setup with chafing dishes',
                'total_quantity' => 20,
                'location' => 'Equipment Storage - Section A',
                'model' => 'BT-4000',
                'serial_number' => 'SN-BT4000-010',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(2),
                'is_active' => true,
            ],
            [
                'equipment_id' => 7,
                'name' => 'Dinner Plates (Set of 12)',
                'code' => 'EQP-007',
                'category' => 'Dining Items',
                'description' => 'Premium ceramic dinner plates',
                'total_quantity' => 120,
                'location' => 'Equipment Storage - Section B',
                'model' => 'DP-5000',
                'serial_number' => 'SN-DP5000-020',
                'condition' => 'Excellent',
                'last_maintenance' => now()->subMonths(6),
                'is_active' => true,
            ],
            [
                'equipment_id' => 8,
                'name' => 'Glassware Set (Set of 6)',
                'code' => 'EQP-008',
                'category' => 'Dining Items',
                'description' => 'Crystal glassware for beverages',
                'total_quantity' => 60,
                'location' => 'Equipment Storage - Section C',
                'model' => 'GW-3000',
                'serial_number' => 'SN-GW3000-015',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(6),
                'is_active' => true,
            ],
            [
                'equipment_id' => 9,
                'name' => 'Silverware Set (Set of 24)',
                'code' => 'EQP-009',
                'category' => 'Dining Items',
                'description' => 'Stainless steel cutlery set',
                'total_quantity' => 50,
                'location' => 'Equipment Storage - Section D',
                'model' => 'SW-4000',
                'serial_number' => 'SN-SW4000-025',
                'condition' => 'Excellent',
                'last_maintenance' => now()->subMonths(6),
                'is_active' => true,
            ],
            [
                'equipment_id' => 10,
                'name' => 'Table Linens (Set of 10)',
                'code' => 'EQP-010',
                'category' => 'Service Equipment',
                'description' => 'Premium tablecloths and napkins',
                'total_quantity' => 30,
                'location' => 'Equipment Storage - Section E',
                'model' => 'TL-2000',
                'serial_number' => 'SN-TL2000-010',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(3),
                'is_active' => true,
            ],
            
            // Delivery Equipment
            [
                'equipment_id' => 11,
                'name' => 'Delivery Van',
                'code' => 'EQP-011',
                'category' => 'Delivery Equipment',
                'description' => 'Refrigerated delivery van for food transport',
                'total_quantity' => 3,
                'location' => 'Fleet Parking - Bay A',
                'model' => 'DV-5000',
                'serial_number' => 'SN-DV5000-003',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(1),
                'is_active' => true,
            ],
            [
                'equipment_id' => 12,
                'name' => 'Insulated Food Carriers',
                'code' => 'EQP-012',
                'category' => 'Delivery Equipment',
                'description' => 'Insulated containers for bulk food transport',
                'total_quantity' => 50,
                'location' => 'Equipment Storage - Section F',
                'model' => 'FC-3000',
                'serial_number' => 'SN-FC3000-030',
                'condition' => 'Excellent',
                'last_maintenance' => now()->subMonths(2),
                'is_active' => true,
            ],
            
            // Catering Equipment
            [
                'equipment_id' => 13,
                'name' => 'Serving Trays',
                'code' => 'EQP-013',
                'category' => 'Service Equipment',
                'description' => 'Large serving trays for buffet service',
                'total_quantity' => 80,
                'location' => 'Equipment Storage - Section G',
                'model' => 'ST-4000',
                'serial_number' => 'SN-ST4000-040',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(4),
                'is_active' => true,
            ],
            [
                'equipment_id' => 14,
                'name' => 'Coffee Urn (50 cups)',
                'code' => 'EQP-014',
                'category' => 'Service Equipment',
                'description' => 'Large capacity coffee urn for events',
                'total_quantity' => 8,
                'location' => 'Equipment Storage - Section H',
                'model' => 'CU-5000',
                'serial_number' => 'SN-CU5000-008',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(3),
                'is_active' => true,
            ],
            [
                'equipment_id' => 15,
                'name' => 'Water Dispenser',
                'code' => 'EQP-015',
                'category' => 'Service Equipment',
                'description' => 'Large-capacity water dispenser for events',
                'total_quantity' => 10,
                'location' => 'Equipment Storage - Section I',
                'model' => 'WD-3000',
                'serial_number' => 'SN-WD3000-005',
                'condition' => 'Excellent',
                'last_maintenance' => now()->subMonths(2),
                'is_active' => true,
            ],
            
            // Cleaning Equipment
            [
                'equipment_id' => 16,
                'name' => 'Industrial Dishwasher',
                'code' => 'EQP-016',
                'category' => 'Cleaning Equipment',
                'description' => 'High-capacity commercial dishwasher',
                'total_quantity' => 2,
                'location' => 'Main Kitchen - Dish Area',
                'model' => 'ID-6000',
                'serial_number' => 'SN-ID6000-002',
                'condition' => 'Good',
                'last_maintenance' => now()->subMonths(1),
                'is_active' => true,
            ],
        ];

        foreach ($equipment as $item) {
            Equipment::updateOrCreate(
                ['equipment_id' => $item['equipment_id']],
                $item
            );
        }
    }
}