<?php
// database/seeders/IngredientSeeder.php - COMPLETE WITH ALL INGREDIENTS FROM PRICE LIST

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ingredient;
use App\Models\InventoryStock;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        $ingredients = [
            // ============================================================
            // PROTEINS - Seafood
            // ============================================================
            [
                'ingredient_id' => 1,
                'name' => 'Fish (Tilapia/Milkfish)',
                'sku' => 'PROT-SF-001',
                'unit' => 'kg',
                'category' => 'Seafood',
                'ingredient_type' => 'direct',
                'unit_cost' => 180.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 2,
                'name' => 'Fish Fillet (Cream Dory)',
                'sku' => 'PROT-SF-002',
                'unit' => 'kg',
                'category' => 'Seafood',
                'ingredient_type' => 'direct',
                'unit_cost' => 280.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 3,
                'name' => 'Sardines (Fresh)',
                'sku' => 'PROT-SF-003',
                'unit' => 'kg',
                'category' => 'Seafood',
                'ingredient_type' => 'direct',
                'unit_cost' => 150.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 4,
                'name' => 'Shrimp (Large)',
                'sku' => 'PROT-SF-004',
                'unit' => 'kg',
                'category' => 'Seafood',
                'ingredient_type' => 'direct',
                'unit_cost' => 450.00,
                'lead_time_days' => 1,
                'yield_percentage' => 85,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // PROTEINS - Chicken
            // ============================================================
            [
                'ingredient_id' => 5,
                'name' => 'Chicken Breast',
                'sku' => 'PROT-CH-001',
                'unit' => 'kg',
                'category' => 'Chicken',
                'ingredient_type' => 'direct',
                'unit_cost' => 200.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 6,
                'name' => 'Chicken Thighs',
                'sku' => 'PROT-CH-002',
                'unit' => 'kg',
                'category' => 'Chicken',
                'ingredient_type' => 'direct',
                'unit_cost' => 180.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 7,
                'name' => 'Chicken Wings',
                'sku' => 'PROT-CH-003',
                'unit' => 'kg',
                'category' => 'Chicken',
                'ingredient_type' => 'direct',
                'unit_cost' => 160.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 8,
                'name' => 'Whole Chicken',
                'sku' => 'PROT-CH-004',
                'unit' => 'kg',
                'category' => 'Chicken',
                'ingredient_type' => 'direct',
                'unit_cost' => 180.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // PROTEINS - Pork
            // ============================================================
            [
                'ingredient_id' => 9,
                'name' => 'Pork Belly',
                'sku' => 'PROT-PK-001',
                'unit' => 'kg',
                'category' => 'Pork',
                'ingredient_type' => 'direct',
                'unit_cost' => 250.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 10,
                'name' => 'Pork Chop',
                'sku' => 'PROT-PK-002',
                'unit' => 'kg',
                'category' => 'Pork',
                'ingredient_type' => 'direct',
                'unit_cost' => 280.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 11,
                'name' => 'Ground Pork',
                'sku' => 'PROT-PK-003',
                'unit' => 'kg',
                'category' => 'Pork',
                'ingredient_type' => 'direct',
                'unit_cost' => 220.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 12,
                'name' => 'Pork Steak Cut',
                'sku' => 'PROT-PK-004',
                'unit' => 'kg',
                'category' => 'Pork',
                'ingredient_type' => 'direct',
                'unit_cost' => 300.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // PROTEINS - Beef
            // ============================================================
            [
                'ingredient_id' => 13,
                'name' => 'Beef Sirloin',
                'sku' => 'PROT-BF-001',
                'unit' => 'kg',
                'category' => 'Beef',
                'ingredient_type' => 'direct',
                'unit_cost' => 380.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 14,
                'name' => 'Beef Stew Meat',
                'sku' => 'PROT-BF-002',
                'unit' => 'kg',
                'category' => 'Beef',
                'ingredient_type' => 'direct',
                'unit_cost' => 320.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 15,
                'name' => 'Roast Beef Cut',
                'sku' => 'PROT-BF-003',
                'unit' => 'kg',
                'category' => 'Beef',
                'ingredient_type' => 'direct',
                'unit_cost' => 450.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 16,
                'name' => 'Beef Strips',
                'sku' => 'PROT-BF-004',
                'unit' => 'kg',
                'category' => 'Beef',
                'ingredient_type' => 'direct',
                'unit_cost' => 350.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // VEGETABLES
            // ============================================================
            [
                'ingredient_id' => 17,
                'name' => 'Onions',
                'sku' => 'VEG-001',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 60.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 18,
                'name' => 'Garlic',
                'sku' => 'VEG-002',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 80.00,
                'lead_time_days' => 1,
                'yield_percentage' => 85,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 19,
                'name' => 'Tomatoes',
                'sku' => 'VEG-003',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 50.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 20,
                'name' => 'Bell Peppers',
                'sku' => 'VEG-004',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 100.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 21,
                'name' => 'Carrots',
                'sku' => 'VEG-005',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 70.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 22,
                'name' => 'Broccoli',
                'sku' => 'VEG-006',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 120.00,
                'lead_time_days' => 1,
                'yield_percentage' => 85,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 23,
                'name' => 'Cabbage',
                'sku' => 'VEG-007',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 45.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 24,
                'name' => 'Potatoes',
                'sku' => 'VEG-008',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 55.00,
                'lead_time_days' => 1,
                'yield_percentage' => 95,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 25,
                'name' => 'Ampalaya (Bitter Melon)',
                'sku' => 'VEG-009',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 80.00,
                'lead_time_days' => 1,
                'yield_percentage' => 85,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 26,
                'name' => 'Lettuce',
                'sku' => 'VEG-010',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 80.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 27,
                'name' => 'String Beans',
                'sku' => 'VEG-011',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 60.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 28,
                'name' => 'Pechay (Bok Choy)',
                'sku' => 'VEG-012',
                'unit' => 'kg',
                'category' => 'Vegetables',
                'ingredient_type' => 'direct',
                'unit_cost' => 50.00,
                'lead_time_days' => 1,
                'yield_percentage' => 90,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // FRUITS
            // ============================================================
            [
                'ingredient_id' => 29,
                'name' => 'Bananas',
                'sku' => 'FRT-001',
                'unit' => 'kg',
                'category' => 'Fruits',
                'ingredient_type' => 'direct',
                'unit_cost' => 60.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 30,
                'name' => 'Mangoes',
                'sku' => 'FRT-002',
                'unit' => 'kg',
                'category' => 'Fruits',
                'ingredient_type' => 'direct',
                'unit_cost' => 100.00,
                'lead_time_days' => 1,
                'yield_percentage' => 85,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 31,
                'name' => 'Pineapple',
                'sku' => 'FRT-003',
                'unit' => 'kg',
                'category' => 'Fruits',
                'ingredient_type' => 'direct',
                'unit_cost' => 80.00,
                'lead_time_days' => 1,
                'yield_percentage' => 80,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 32,
                'name' => 'Coconut (Buko)',
                'sku' => 'FRT-004',
                'unit' => 'pcs',
                'category' => 'Fruits',
                'ingredient_type' => 'direct',
                'unit_cost' => 30.00,
                'lead_time_days' => 1,
                'yield_percentage' => 60,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 33,
                'name' => 'Lemons',
                'sku' => 'FRT-005',
                'unit' => 'kg',
                'category' => 'Fruits',
                'ingredient_type' => 'direct',
                'unit_cost' => 90.00,
                'lead_time_days' => 1,
                'yield_percentage' => 85,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 34,
                'name' => 'Oranges',
                'sku' => 'FRT-006',
                'unit' => 'kg',
                'category' => 'Fruits',
                'ingredient_type' => 'direct',
                'unit_cost' => 80.00,
                'lead_time_days' => 1,
                'yield_percentage' => 85,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // DRY GOODS & STAPLES
            // ============================================================
            [
                'ingredient_id' => 35,
                'name' => 'Rice',
                'sku' => 'DRY-001',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 55.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 36,
                'name' => 'Spaghetti Pasta',
                'sku' => 'DRY-002',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 80.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 37,
                'name' => 'Lasagna Sheets',
                'sku' => 'DRY-003',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 120.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 38,
                'name' => 'Pancit Canton Noodles',
                'sku' => 'DRY-004',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 70.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 39,
                'name' => 'Sotanghon (Glass Noodles)',
                'sku' => 'DRY-005',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 90.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 40,
                'name' => 'All-Purpose Flour',
                'sku' => 'DRY-006',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 60.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 41,
                'name' => 'Breadcrumbs',
                'sku' => 'DRY-007',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 90.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 42,
                'name' => 'White Sugar',
                'sku' => 'DRY-008',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 70.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 43,
                'name' => 'Brown Sugar',
                'sku' => 'DRY-009',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 75.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 44,
                'name' => 'Salt',
                'sku' => 'DRY-010',
                'unit' => 'kg',
                'category' => 'Dry Goods',
                'ingredient_type' => 'direct',
                'unit_cost' => 20.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // COOKING OILS & VINEGAR
            // ============================================================
            [
                'ingredient_id' => 45,
                'name' => 'Cooking Oil',
                'sku' => 'OIL-001',
                'unit' => 'L',
                'category' => 'Oils & Vinegars',
                'ingredient_type' => 'direct',
                'unit_cost' => 120.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 46,
                'name' => 'Olive Oil',
                'sku' => 'OIL-002',
                'unit' => 'L',
                'category' => 'Oils & Vinegars',
                'ingredient_type' => 'direct',
                'unit_cost' => 300.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 47,
                'name' => 'Vinegar',
                'sku' => 'OIL-003',
                'unit' => 'L',
                'category' => 'Oils & Vinegars',
                'ingredient_type' => 'direct',
                'unit_cost' => 50.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 48,
                'name' => 'Balsamic Vinegar',
                'sku' => 'OIL-004',
                'unit' => 'L',
                'category' => 'Oils & Vinegars',
                'ingredient_type' => 'direct',
                'unit_cost' => 280.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // SAUCES & CONDIMENTS
            // ============================================================
            [
                'ingredient_id' => 49,
                'name' => 'Soy Sauce',
                'sku' => 'SAU-001',
                'unit' => 'L',
                'category' => 'Sauces',
                'ingredient_type' => 'direct',
                'unit_cost' => 60.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 50,
                'name' => 'Oyster Sauce',
                'sku' => 'SAU-002',
                'unit' => 'L',
                'category' => 'Sauces',
                'ingredient_type' => 'direct',
                'unit_cost' => 130.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 51,
                'name' => 'Worcestershire Sauce',
                'sku' => 'SAU-003',
                'unit' => 'L',
                'category' => 'Sauces',
                'ingredient_type' => 'direct',
                'unit_cost' => 200.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 52,
                'name' => 'Ketchup',
                'sku' => 'SAU-004',
                'unit' => 'L',
                'category' => 'Sauces',
                'ingredient_type' => 'direct',
                'unit_cost' => 80.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 53,
                'name' => 'Mayonnaise',
                'sku' => 'SAU-005',
                'unit' => 'L',
                'category' => 'Sauces',
                'ingredient_type' => 'direct',
                'unit_cost' => 150.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 54,
                'name' => 'Honey',
                'sku' => 'SAU-006',
                'unit' => 'L',
                'category' => 'Sauces',
                'ingredient_type' => 'direct',
                'unit_cost' => 250.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 55,
                'name' => 'Sweet Chili Sauce',
                'sku' => 'SAU-007',
                'unit' => 'L',
                'category' => 'Sauces',
                'ingredient_type' => 'direct',
                'unit_cost' => 120.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // DAIRY & EGGS
            // ============================================================
            [
                'ingredient_id' => 56,
                'name' => 'Fresh Milk',
                'sku' => 'DRY-011',
                'unit' => 'L',
                'category' => 'Dairy',
                'ingredient_type' => 'direct',
                'unit_cost' => 100.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 57,
                'name' => 'All-Purpose Cream',
                'sku' => 'DRY-012',
                'unit' => 'L',
                'category' => 'Dairy',
                'ingredient_type' => 'direct',
                'unit_cost' => 150.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 58,
                'name' => 'Cheddar Cheese',
                'sku' => 'DRY-013',
                'unit' => 'kg',
                'category' => 'Dairy',
                'ingredient_type' => 'direct',
                'unit_cost' => 300.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 59,
                'name' => 'Parmesan Cheese',
                'sku' => 'DRY-014',
                'unit' => 'kg',
                'category' => 'Dairy',
                'ingredient_type' => 'direct',
                'unit_cost' => 400.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 60,
                'name' => 'Butter',
                'sku' => 'DRY-015',
                'unit' => 'kg',
                'category' => 'Dairy',
                'ingredient_type' => 'direct',
                'unit_cost' => 200.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 61,
                'name' => 'Eggs',
                'sku' => 'DRY-016',
                'unit' => 'tray',
                'category' => 'Dairy',
                'ingredient_type' => 'direct',
                'unit_cost' => 120.00,
                'lead_time_days' => 1,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // SPICES & HERBS
            // ============================================================
            [
                'ingredient_id' => 62,
                'name' => 'Black Pepper (Ground)',
                'sku' => 'SPC-001',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 200.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 63,
                'name' => 'Bay Leaves',
                'sku' => 'SPC-002',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 150.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 64,
                'name' => 'Chili Flakes',
                'sku' => 'SPC-003',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 180.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 65,
                'name' => 'Cinnamon Sticks',
                'sku' => 'SPC-004',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 250.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 66,
                'name' => 'Cumin Powder',
                'sku' => 'SPC-005',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 220.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 67,
                'name' => 'Paprika',
                'sku' => 'SPC-006',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 180.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 68,
                'name' => 'Garlic Powder',
                'sku' => 'SPC-007',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 160.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 69,
                'name' => 'Onion Powder',
                'sku' => 'SPC-008',
                'unit' => 'kg',
                'category' => 'Spices',
                'ingredient_type' => 'direct',
                'unit_cost' => 150.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],

            // ============================================================
            // BAKING ESSENTIALS
            // ============================================================
            [
                'ingredient_id' => 70,
                'name' => 'Baking Powder',
                'sku' => 'BKE-001',
                'unit' => 'kg',
                'category' => 'Baking',
                'ingredient_type' => 'direct',
                'unit_cost' => 150.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 71,
                'name' => 'Cocoa Powder',
                'sku' => 'BKE-002',
                'unit' => 'kg',
                'category' => 'Baking',
                'ingredient_type' => 'direct',
                'unit_cost' => 300.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
            [
                'ingredient_id' => 72,
                'name' => 'Vanilla Extract',
                'sku' => 'BKE-003',
                'unit' => 'L',
                'category' => 'Baking',
                'ingredient_type' => 'direct',
                'unit_cost' => 400.00,
                'lead_time_days' => 2,
                'yield_percentage' => 100,
                'reuse_factor' => 1.00,
                'is_active' => true,
            ],
        ];

        foreach ($ingredients as $ingredient) {
            $created = Ingredient::updateOrCreate(
                ['ingredient_id' => $ingredient['ingredient_id']],
                [
                    'name' => $ingredient['name'],
                    'sku' => $ingredient['sku'],
                    'unit' => $ingredient['unit'],
                    'category' => $ingredient['category'],
                    'ingredient_type' => $ingredient['ingredient_type'],
                    'unit_cost' => $ingredient['unit_cost'],
                    'lead_time_days' => $ingredient['lead_time_days'],
                    'yield_percentage' => $ingredient['yield_percentage'] ?? 100,
                    'reuse_factor' => $ingredient['reuse_factor'] ?? 1.00,
                    'is_active' => $ingredient['is_active'],
                ]
            );

            // Create initial stock for each ingredient
            $currentQuantity = rand(50, 200);
            $reservedQuantity = rand(0, 20);
            $minimumQuantity = 10;
            $maximumQuantity = 300;
            $reorderPoint = 15;

            InventoryStock::updateOrCreate(
                ['ingredient_id' => $created->ingredient_id],
                [
                    'current_quantity' => $currentQuantity,
                    'reserved_quantity' => $reservedQuantity,
                    'minimum_quantity' => $minimumQuantity,
                    'maximum_quantity' => $maximumQuantity,
                    'max_stock_level' => $maximumQuantity,
                    'reorder_point' => $reorderPoint,
                    'storage_location' => 'Warehouse ' . chr(rand(65, 68)) . rand(1, 3),
                    'expiry_date' => now()->addMonths(rand(3, 12)),
                    'last_restocked_at' => now()->subDays(rand(1, 30)),
                    'created_at' => now()->subDays(rand(1, 60)),
                    'updated_at' => now(),
                ]
            );
        }
    }
}