<?php
// database/seeders/MenuItemSeeder.php - FIXED DUPLICATE INGREDIENTS

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MenuItem;
use App\Models\MealCategory;
use App\Models\RecipeIngredient;
use App\Models\Ingredient;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing recipe ingredients first to avoid duplicates
        RecipeIngredient::truncate();

        $menuItems = [
            // ==================== SEAFOOD ====================
            [
                'menu_item_id' => 1,
                'category_id' => 1,
                'name' => 'Sweet & Sour Fish',
                'slug' => 'sweet-sour-fish',
                'description' => 'Fried fish fillet with sweet and sour sauce',
                'price' => 1500.00,
                'cost_to_make' => 650.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 2, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 20, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 42, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 47, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 40, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 2,
                'category_id' => 1,
                'name' => 'Spanish Sardine',
                'slug' => 'spanish-sardine',
                'description' => 'Spanish-style sardines in tomato sauce',
                'price' => 1450.00,
                'cost_to_make' => 600.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 3, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.06, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 47, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.03, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 3,
                'category_id' => 1,
                'name' => 'Steamed Fish',
                'slug' => 'steamed-fish',
                'description' => 'Fresh fish steamed with ginger and scallions',
                'price' => 1700.00,
                'cost_to_make' => 750.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 1, 'quantity_per_pax' => 0.25, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.01, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 4,
                'category_id' => 1,
                'name' => 'Singulaw',
                'slug' => 'singulaw',
                'description' => 'Traditional fish dish with coconut milk and spices',
                'price' => 1600.00,
                'cost_to_make' => 700.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 1, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                    ['ingredient_id' => 56, 'quantity_per_pax' => 0.05, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 5,
                'category_id' => 1,
                'name' => 'Sautéed Shrimp in Butter/Garlic',
                'slug' => 'sauteed-shrimp-butter-garlic',
                'description' => 'Juicy shrimp sautéed in butter and garlic',
                'price' => 1550.00,
                'cost_to_make' => 700.00,
                'prep_time_minutes' => 20,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 4, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],

            // ==================== CHICKEN ====================
            [
                'menu_item_id' => 6,
                'category_id' => 2,
                'name' => 'Buttered Chicken',
                'slug' => 'buttered-chicken',
                'description' => 'Tender chicken in creamy butter sauce',
                'price' => 1300.00,
                'cost_to_make' => 550.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 5, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 7,
                'category_id' => 2,
                'name' => 'Golden Fried Chicken',
                'slug' => 'golden-fried-chicken',
                'description' => 'Crispy golden fried chicken',
                'price' => 1300.00,
                'cost_to_make' => 550.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 6, 'quantity_per_pax' => 0.25, 'unit' => 'kg'],
                    ['ingredient_id' => 40, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.05, 'unit' => 'L'],
                    ['ingredient_id' => 44, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 8,
                'category_id' => 2,
                'name' => 'Sweet Chili Wings',
                'slug' => 'sweet-chili-wings',
                'description' => 'Chicken wings glazed with sweet chili sauce',
                'price' => 1250.00,
                'cost_to_make' => 500.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 7, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 42, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.03, 'unit' => 'L'],
                    ['ingredient_id' => 64, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                    ['ingredient_id' => 55, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 9,
                'category_id' => 2,
                'name' => 'Garlic Parmesan Chicken',
                'slug' => 'garlic-parmesan-chicken',
                'description' => 'Chicken with garlic parmesan crust',
                'price' => 1250.00,
                'cost_to_make' => 550.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 5, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 58, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 40, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.01, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 10,
                'category_id' => 2,
                'name' => 'Roasted Chicken',
                'slug' => 'roasted-chicken',
                'description' => 'Herb-roasted whole chicken',
                'price' => 1400.00,
                'cost_to_make' => 600.00,
                'prep_time_minutes' => 45,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 8, 'quantity_per_pax' => 0.25, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],

            // ==================== PORK ====================
            [
                'menu_item_id' => 11,
                'category_id' => 3,
                'name' => 'Lumpia Shanghai',
                'slug' => 'lumpia-shanghai',
                'description' => 'Crispy spring rolls with pork filling',
                'price' => 900.00,
                'cost_to_make' => 380.00,
                'prep_time_minutes' => 30,
                'serving_size' => 24,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 11, 'quantity_per_pax' => 0.1, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.01, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 61, 'quantity_per_pax' => 0.5, 'unit' => 'pcs'],
                    ['ingredient_id' => 41, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.03, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 12,
                'category_id' => 3,
                'name' => 'Pork Chop',
                'slug' => 'pork-chop',
                'description' => 'Grilled pork chops with savory marinade',
                'price' => 1400.00,
                'cost_to_make' => 600.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 10, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.03, 'unit' => 'L'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 13,
                'category_id' => 3,
                'name' => 'Bola-Bola',
                'slug' => 'bola-bola',
                'description' => 'Pork meatballs in rich sauce',
                'price' => 1200.00,
                'cost_to_make' => 500.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 11, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.01, 'unit' => 'kg'],
                    ['ingredient_id' => 61, 'quantity_per_pax' => 0.5, 'unit' => 'pcs'],
                    ['ingredient_id' => 41, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 14,
                'category_id' => 3,
                'name' => 'Humba',
                'slug' => 'humba',
                'description' => 'Braised pork belly in sweet soy sauce',
                'price' => 1500.00,
                'cost_to_make' => 650.00,
                'prep_time_minutes' => 45,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 9, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.03, 'unit' => 'L'],
                    ['ingredient_id' => 43, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 47, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 63, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 15,
                'category_id' => 3,
                'name' => 'Pork Steak',
                'slug' => 'pork-steak',
                'description' => 'Tender pork steak with savory gravy',
                'price' => 1500.00,
                'cost_to_make' => 650.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 12, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 51, 'quantity_per_pax' => 0.01, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 16,
                'category_id' => 3,
                'name' => 'Binagongan',
                'slug' => 'binagongan',
                'description' => 'Pork with fermented shrimp paste',
                'price' => 1400.00,
                'cost_to_make' => 600.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 9, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 20, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 17,
                'category_id' => 3,
                'name' => 'Pork in White Sauce',
                'slug' => 'pork-white-sauce',
                'description' => 'Pork in creamy white sauce',
                'price' => 1400.00,
                'cost_to_make' => 600.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 10, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 56, 'quantity_per_pax' => 0.04, 'unit' => 'L'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 40, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                ],
            ],

            // ==================== BEEF ====================
            [
                'menu_item_id' => 18,
                'category_id' => 4,
                'name' => 'Beef with Ampalaya',
                'slug' => 'beef-ampalaya',
                'description' => 'Beef with bitter melon stir-fry',
                'price' => 1400.00,
                'cost_to_make' => 650.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 16, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 25, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 19,
                'category_id' => 4,
                'name' => 'Beef Steak',
                'slug' => 'beef-steak',
                'description' => 'Grilled beef steak with special marinade',
                'price' => 1600.00,
                'cost_to_make' => 750.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 13, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 51, 'quantity_per_pax' => 0.01, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 20,
                'category_id' => 4,
                'name' => 'Beef with Broccoli',
                'slug' => 'beef-broccoli',
                'description' => 'Beef stir-fried with fresh broccoli',
                'price' => 1650.00,
                'cost_to_make' => 750.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 16, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 22, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 50, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 21,
                'category_id' => 4,
                'name' => 'Beef with 3 Kinds of Mushroom',
                'slug' => 'beef-three-mushrooms',
                'description' => 'Beef with mixed mushrooms in savory sauce',
                'price' => 1650.00,
                'cost_to_make' => 750.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 16, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 50, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 22,
                'category_id' => 4,
                'name' => 'Beef Stew',
                'slug' => 'beef-stew',
                'description' => 'Slow-cooked beef stew with vegetables',
                'price' => 1600.00,
                'cost_to_make' => 700.00,
                'prep_time_minutes' => 60,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 14, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 24, 'quantity_per_pax' => 0.06, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                    ['ingredient_id' => 63, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 23,
                'category_id' => 4,
                'name' => 'Roast Beef',
                'slug' => 'roast-beef',
                'description' => 'Slow-roasted beef with herb crust',
                'price' => 1800.00,
                'cost_to_make' => 850.00,
                'prep_time_minutes' => 60,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 15, 'quantity_per_pax' => 0.25, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 24,
                'category_id' => 4,
                'name' => 'Beef in White Sauce',
                'slug' => 'beef-white-sauce',
                'description' => 'Beef in creamy white sauce',
                'price' => 1800.00,
                'cost_to_make' => 800.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 13, 'quantity_per_pax' => 0.2, 'unit' => 'kg'],
                    ['ingredient_id' => 56, 'quantity_per_pax' => 0.04, 'unit' => 'L'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 40, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 62, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],

            // ==================== VEGETABLES ====================
            [
                'menu_item_id' => 25,
                'category_id' => 5,
                'name' => 'Pinakbet',
                'slug' => 'pinakbet',
                'description' => 'Ilocano vegetable stew with bagoong',
                'price' => 950.00,
                'cost_to_make' => 380.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 24, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 26,
                'category_id' => 5,
                'name' => 'Chopsuey',
                'slug' => 'chopsuey',
                'description' => 'Mixed vegetables stir-fry',
                'price' => 1000.00,
                'cost_to_make' => 400.00,
                'prep_time_minutes' => 20,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 22, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 20, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 23, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 27,
                'category_id' => 5,
                'name' => 'Four Season Vegetables',
                'slug' => 'four-season-vegetables',
                'description' => 'Four season vegetables in light sauce',
                'price' => 1250.00,
                'cost_to_make' => 500.00,
                'prep_time_minutes' => 20,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 22, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 20, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.01, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 28,
                'category_id' => 5,
                'name' => 'Buttered Vegetables',
                'slug' => 'buttered-vegetables',
                'description' => 'Mixed vegetables in butter sauce',
                'price' => 1200.00,
                'cost_to_make' => 480.00,
                'prep_time_minutes' => 20,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 22, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 20, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 44, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],

            // ==================== PASTA & NOODLES ====================
            [
                'menu_item_id' => 29,
                'category_id' => 6,
                'name' => 'Pancit Canton Guisado',
                'slug' => 'pancit-canton-guisado',
                'description' => 'Stir-fried noodles with vegetables and meat',
                'price' => 900.00,
                'cost_to_make' => 380.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 38, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 23, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 30,
                'category_id' => 6,
                'name' => 'Sotanghon',
                'slug' => 'sotanghon',
                'description' => 'Glass noodle soup with chicken and vegetables',
                'price' => 1100.00,
                'cost_to_make' => 480.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 39, 'quantity_per_pax' => 0.1, 'unit' => 'kg'],
                    ['ingredient_id' => 5, 'quantity_per_pax' => 0.1, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 23, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 31,
                'category_id' => 6,
                'name' => 'Bam-E',
                'slug' => 'bam-e',
                'description' => 'Mixed noodles with vegetables and meat',
                'price' => 950.00,
                'cost_to_make' => 400.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 38, 'quantity_per_pax' => 0.1, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 23, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 49, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 32,
                'category_id' => 6,
                'name' => 'Spaghetti',
                'slug' => 'spaghetti',
                'description' => 'Classic spaghetti with meat sauce',
                'price' => 1500.00,
                'cost_to_make' => 650.00,
                'prep_time_minutes' => 30,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 36, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 11, 'quantity_per_pax' => 0.1, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 58, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 45, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 33,
                'category_id' => 6,
                'name' => 'Carbonara',
                'slug' => 'carbonara',
                'description' => 'Creamy pasta with bacon and parmesan',
                'price' => 1700.00,
                'cost_to_make' => 750.00,
                'prep_time_minutes' => 25,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 36, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 61, 'quantity_per_pax' => 1, 'unit' => 'pcs'],
                    ['ingredient_id' => 56, 'quantity_per_pax' => 0.05, 'unit' => 'L'],
                    ['ingredient_id' => 57, 'quantity_per_pax' => 0.04, 'unit' => 'L'],
                    ['ingredient_id' => 59, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.01, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 34,
                'category_id' => 6,
                'name' => 'Lasagna',
                'slug' => 'lasagna',
                'description' => 'Baked pasta with meat sauce and cheese',
                'price' => 1900.00,
                'cost_to_make' => 850.00,
                'prep_time_minutes' => 45,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 37, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 11, 'quantity_per_pax' => 0.12, 'unit' => 'kg'],
                    ['ingredient_id' => 19, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 18, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 58, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 60, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 56, 'quantity_per_pax' => 0.05, 'unit' => 'L'],
                ],
            ],

            // ==================== DESSERTS & SALADS ====================
            [
                'menu_item_id' => 35,
                'category_id' => 7,
                'name' => 'Fruit Salad',
                'slug' => 'fruit-salad',
                'description' => 'Fresh mixed fruit salad with cream',
                'price' => 1000.00,
                'cost_to_make' => 420.00,
                'prep_time_minutes' => 15,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 30, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 29, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 31, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 57, 'quantity_per_pax' => 0.04, 'unit' => 'L'],
                    ['ingredient_id' => 42, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 36,
                'category_id' => 7,
                'name' => 'Potato Salad',
                'slug' => 'potato-salad',
                'description' => 'Creamy potato salad with vegetables',
                'price' => 1200.00,
                'cost_to_make' => 500.00,
                'prep_time_minutes' => 20,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 24, 'quantity_per_pax' => 0.15, 'unit' => 'kg'],
                    ['ingredient_id' => 53, 'quantity_per_pax' => 0.02, 'unit' => 'L'],
                    ['ingredient_id' => 21, 'quantity_per_pax' => 0.03, 'unit' => 'kg'],
                    ['ingredient_id' => 17, 'quantity_per_pax' => 0.01, 'unit' => 'kg'],
                    ['ingredient_id' => 44, 'quantity_per_pax' => 0.005, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 37,
                'category_id' => 7,
                'name' => 'Mango Tapioca',
                'slug' => 'mango-tapioca',
                'description' => 'Sweet mango tapioca dessert',
                'price' => 1000.00,
                'cost_to_make' => 420.00,
                'prep_time_minutes' => 20,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => true,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 30, 'quantity_per_pax' => 0.08, 'unit' => 'kg'],
                    ['ingredient_id' => 56, 'quantity_per_pax' => 0.04, 'unit' => 'L'],
                    ['ingredient_id' => 42, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                    ['ingredient_id' => 57, 'quantity_per_pax' => 0.03, 'unit' => 'L'],
                ],
            ],
            [
                'menu_item_id' => 38,
                'category_id' => 7,
                'name' => 'Buko Salad',
                'slug' => 'buko-salad',
                'description' => 'Coconut salad with fruits and cream',
                'price' => 1000.00,
                'cost_to_make' => 420.00,
                'prep_time_minutes' => 15,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 32, 'quantity_per_pax' => 0.06, 'unit' => 'pcs'],
                    ['ingredient_id' => 30, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 31, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 57, 'quantity_per_pax' => 0.04, 'unit' => 'L'],
                    ['ingredient_id' => 42, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                ],
            ],
            [
                'menu_item_id' => 39,
                'category_id' => 7,
                'name' => 'Fresh Fruit Season',
                'slug' => 'fresh-fruit-season',
                'description' => 'Seasonal fresh fruit platter',
                'price' => 950.00,
                'cost_to_make' => 400.00,
                'prep_time_minutes' => 15,
                'serving_size' => 8,
                'is_available' => true,
                'is_popular' => false,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_halal' => true,
                'ingredients' => [
                    ['ingredient_id' => 30, 'quantity_per_pax' => 0.05, 'unit' => 'kg'],
                    ['ingredient_id' => 29, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 31, 'quantity_per_pax' => 0.04, 'unit' => 'kg'],
                    ['ingredient_id' => 33, 'quantity_per_pax' => 0.02, 'unit' => 'kg'],
                ],
            ],
        ];

        foreach ($menuItems as $itemData) {
            $ingredients = $itemData['ingredients'];
            unset($itemData['ingredients']);

            $menuItem = MenuItem::updateOrCreate(
                ['menu_item_id' => $itemData['menu_item_id']],
                $itemData
            );

            // Delete existing recipe ingredients for this menu item
            RecipeIngredient::where('menu_item_id', $menuItem->menu_item_id)->delete();
            
            // Insert new recipe ingredients
            foreach ($ingredients as $ingredient) {
                RecipeIngredient::create([
                    'menu_item_id' => $menuItem->menu_item_id,
                    'ingredient_id' => $ingredient['ingredient_id'],
                    'quantity_per_pax' => $ingredient['quantity_per_pax'],
                    'unit' => $ingredient['unit'],
                ]);
            }
        }
    }
}